trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Substitute BIN for your bin directory.
    # Substitute VERSION for the current released version.
    # Substitute BINARY_NAME for "buf", "protoc-gen-buf-check-breaking", or "protoc-gen-buf-check-lint".
    BIN="$(Pipeline.Workspace)/.bin/" && \
    VERSION="0.15.0" && \
    BINARY_NAME="buf" && \
      mkdir -p "${BIN}" && \
      curl -sSL \
        "https://github.com/bufbuild/buf/releases/download/v${VERSION}/${BINARY_NAME}-$(uname -s)-$(uname -m)" \
        -o "${BIN}/${BINARY_NAME}" && \
      chmod +x "${BIN}/${BINARY_NAME}" && \
      echo "##vso[task.prependpath]$(Pipeline.Workspace)/.bin/"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Get dependencies'

- script: |
    buf ls-files
    buf check lint
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Lint'

- script: |
    buf image build -o ledger-image.bin --file protos/contract_messages.proto --file protos/ledger_messages.proto
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Build'

- publish: $(System.DefaultWorkingDirectory)/ledger-image.bin
  artifact: LedgerImage
