[package]
name = "fabric_ledger_protos"
version = "0.1.0"
authors = ["Hyperledger Fabric Developers"]
license = "Apache-2.0"
repository = "https://github.com/hyperledgendary/fabric-ledger-protos-rust"
edition = "2018"

[dependencies]
# protobuf handling
prost = "0.6.1"
prost-types = "0.6.1"
